[project]
name = "research_agent"
version = "0.0.1"
description = "Starter project research agent"
authors = [
    { name = "Name <Email>" }
]
license = { text = "MIT" }
requires-python = ">=3.10"

dependencies = [
    "agentstack[crewai]>=0.3.5",
    "requests>=2.30",
]
